title: Game Hubs
description: "Game Hubs: A platform for gamers to share their experiences and connect with others."
owner_name: Ian Manangan
github_username: Im2008
github_repo: "GameHubss" 
baseurl: "/GameHubss"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/Search.md